services:
  api:
    build:
      context: api/
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - cat-network
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "4543:8080"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - api
    networks:
      - cat-network

networks:
  cat-network:
    driver: bridge